{% set name = "jupyterlite-sphinx" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlite_sphinx-{{ version }}.tar.gz
  sha256: c34b6ff76ab05ed981867d4d5a1d5773b4eca7e26b833677fd2ad1042162e5bf

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - docutils
    - jupyter_server
    - jupyterlab_server
    - jupyterlite-core >=0.2.0,<0.6.0
    - jupytext
    - nbformat
    - sphinx >=4

test:
  imports:
    - jupyterlite_sphinx
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyterlite/jupyterlite-sphinx
  summary: Sphinx extension for deploying JupyterLite
  doc_url: https://jupyterlite-sphinx.readthedocs.io
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agriyakhetarpal
    - Carreau
    - steppi
    - jtpio
    - martinRenou
