{% set name = "jupyterlite-sphinx" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlite_sphinx-{{ version }}.tar.gz
  sha256: c90f4a7dba4742c7b0ca41df1845484f29dc044b9f54c5f8ee408dba7d837f2f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - docutils
    - jupyter_server
    - jupyterlab_server
    - jupyterlite-core >=0.2.0,<0.5.0
    - sphinx >=4

test:
  imports:
    - jupyterlite_sphinx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyterlite/jupyterlite-sphinx
  summary: Sphinx extension for deploying JupyterLite
  doc_url: https://jupyterlite-sphinx.readthedocs.io
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Carreau
    - steppi
    - jtpio
    - martinRenou
